---
- hosts: all
  user: vagrant
  tasks:
  - name: updates a server
    apt: update_cache=yes
    sudo: true
  - name: install software-properties-common
    apt: pkg=software-properties-common
    sudo: true

  - name: install curl
    apt: pkg=curl
    sudo: true

  # PHP5
  - name: add php5 ppa
    apt_repository: repo='ppa:ondrej/php5'
    sudo: true
  - name: install PHP5 packages
    apt: name={{ item }} state=latest
    sudo: true
    with_items:
      - php5
      - libapache2-mod-php5
      - php5-cli
      - php5-dev
      - php5-mysql
      - php-pear
      - php5-mcrypt
      - php5-gd
      - php5-curl
      - php5-xdebug
      - php5-memcache
      - php5-memcached
      - php5-readline
      - php5-sqlite
      - php5-json

  # MySQL
  - name: install MySQL
    apt: name={{ item }} state=latest
    sudo: true
    with_items:
      - mysql-server
      - mysql-client
      - python-mysqldb

  - name: mysql template
    template: src=templates/my.cnf dest=/etc/mysql/my.cnf
    sudo: true

  - name: restart mysql
    command: service mysql restart
    # action: service name=mysql state=restarted
    sudo: true

  - name: add mysql user
    sudo: true
    mysql_user: name=vagrant
                host={{ item }}
                password=vagrant priv=*.*:ALL,GRANT
                login_user=root
                login_password=
    with_items:
      - '%'
      - localhost

  # Apache
  - name: install apache
    apt: name={{ item }} state=latest
    sudo: true
    with_items:
      - apache2

  - name: apache template
    template: src=templates/000-default.conf dest=/etc/apache2/sites-available/000-default.conf
    sudo: true

  - name: enable apache rewrite module
    action: command a2enmod rewrite
    sudo: true

  - name: restart apache2
    action: service name=apache2 state=restarted
    sudo: true

  # zsh
  - name: install zsh
    apt: pkg=zsh
    sudo: true

  - name: change shell
    command: chsh -s /bin/zsh vagrant
    sudo: true

  - git: repo=ssh://git@github.com/tamanyan/oh-my-zsh.git dest=/home/vagrant/.oh-my-zsh accept_hostkey=yes
  - copy: src=templates/.zshrc dest=/home/vagrant/.zshrc

  # percol
  - name: install percol
    command: pip install percol
    sudo: true

  # copy
  - file: path=/home/vagrant/.percol.d state=directory
  - copy: src=templates/rc.py dest=/home/vagrant/.percol.d/rc.py
  # set locale
  - copy: src=templates/locale dest=/etc/default/locale
    sudo: true

  # gitconfig
  - copy: src=templates/.gitconfig dest=/home/vagrant/.gitconfig
